name: Bug Report
description: "Found a bug? We'd appreciate if you'd first search through our open issues and docs, to make sure the issue isn't already known."
labels: ["Bugs"]
body:
  - type: checkboxes
    attributes:
      label: "Dupe Check"
      options:
        - label: "I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates"
          required: true
  - type: input
    id: "service"
    attributes:
      label: "Service this pertains to."
      description: "This should be provided so we know where to start looking."
    validations:
      required: false
  - type: input
    id: "service"
    attributes:
      label: "Service this pertains to."
      description: "This should be provided so we know where to start looking."
    validations:
      required: false
  - type: dropdown
    id: "browser"
    attributes:
      label: "Browser"
      multiple: false
      options:
        - Chrome Based
        - Firefox
        - Other
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "To reproduce"
      description: "Bug reports with clear reproduction will get prioritized higher and addressed more quickly."
      placeholder: "Steps to reproduce: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error '...'"
    validations:
      required: true
  - type: dropdown
    id: "blocker"
    attributes:
      label: "Does this block you from using Orion daily?"
      description: "All feedback will be reviewed, even if you select 'No'."
      multiple: false
      options:
        - "No"
        - "Yes, this issue prevents me from using Orion daily."
    validations:
      required: true
