name: Bug Report
description: "Found a bug? We'd appreciate if you'd first search through our open issues and docs, to make sure the issue isn't already known."
labels: ["Bugs"]
body:
  - type: checkboxes
    attributes:
      label: "Dupe Check"
      options:
        - label: "I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates"
          required: true
  - type: dropdown
    id: "browser"
    attributes:
      label: "Browser"
      multiple: false
      options:
        - Chrome Based
        - Firefox
        - Other
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "To reproduce"
      description: "Bug reports with clear reproduction will get prioritized higher and addressed more quickly."
      placeholder: "Steps to reproduce: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error '...'"
    validations:
      required: true
  - type: textarea
    id: "expected-behavior"
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: Tell us what you expect to see.
    validations:
      required: false
  - type: textarea
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots/videos to help explain your problem. While optional, screenshots help expedite the time in which your bug is addressed."
    validations:
      required: false
  - type: dropdown
    id: "regression"
    attributes:
      label: "Regression"
      description: "Is this a regression (used to work in a previous Orion version)?"
      multiple: false
      options:
        - "No, this bug or issue has existed throughout my experience using Orion"
        - "Yes, this bug started recently or with an X Orion version"
    validations:
      required: true
  - type: input
    id: "orion-version-regression-date"
    attributes:
      label: "Recent working Orion date"
      description: "Most recent date that Orion worked as expected"
    validations:
      required: false
  - type: dropdown
    id: "blocker"
    attributes:
      label: "Does this block you from using Orion daily?"
      description: "All feedback will be reviewed, even if you select 'No'."
      multiple: false
      options:
        - "No"
        - "Yes, this issue prevents me from using Orion daily."
    validations:
      required: true
